name: Magma AGW Build
on: [push]
jobs:
  Magma-AGW-Build:
    runs-on: macos-latest
    steps:
    - run: echo "::set-output name=date::$(date +'%m-%d-%Y--%H-%M-%S')"
      id: date
    - uses: actions/checkout@v2
    - run: ./build.sh
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ steps.date.outputs.date }}
        prerelease: false
        files: |
          *.deb
